apiVersion: apps/v1
kind: Deployment
metadata:
  name: autogen-ui-be
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autogen-ui-be
  template:
    metadata:
      labels:
        app: autogen-ui-be
    spec:
      imagePullSecrets:
      - name: motiong-registry-key
      containers:
      - name: autogen-ui-be
        image: motiongcloud.azurecr.io/zz-autogen-be:0.0.4
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: autogen-ui-be
  namespace: dev
spec:
  selector:
    app: autogen-ui-be
  ports:
    - protocol: TCP
      port: 8081
      name: http
      targetPort: 8081
  type: LoadBalancer